### ISSUE TITLE
RuntimeError when fine-tuning with multi GPU: "Distributed package doesn't have NCCL built in"

### ISSUE THREAD

**Issue by BaoBaoGitHub** [meta-llama/llama-recipes#126]
### System Info

PyTorch version : 2.01 and nightly
NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2
I installed cuda 11.8 with conda  by `pip install -r requirements.txt` .
Ubuntu 2204 with 3 RTX3090s.  
NCCL version : 2.18.3

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

I want to run fine-tuning example code but have somes problems.

**Pytorch 2.01**

Firstly, I want to fine-tune with pytorch 2.01 and fsdp.
The command are as follows.

```
torchrun --nnodes 1 --nproc_per_node 3  ./llama_finetuning.py --enable_fsdp --model_name <converted hugging face llama2 weights path>/7B --output_dir <output path>
```

Then I got `torch.cuda.OutOfMemoryError: CUDA out of memory` error message.

So I decided to fine-tune using FSDP + PEFT described by doc `Fine-tuning with Multi GPU` .

**Pytorch Nightly**

The doc `Fine-tuning with Multi GPU` told me Pytorch Nightly was needed.

So I created a new conda env and installed pytorch by `conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch-nightly -c nvidia` .

After that, I removed the first two lines in requiremts.txt "-f https://download.pytorch.org/whl/torch_stable.html" and 
"torch==2.0.1+cu118" and execute `pip install -r requirements.txt` .

Then I ran `torchrun --nnodes 1 --nproc_per_node 3  ./llama_finetuning.py --enable_fsdp --model_name <converted hugging face llama2 weights path>/7B --use_peft --peft_method lora --output_dir <output path>` .

But I got error `RuntimeError: Distributed package doesn't have NCCL built in`.

So I installed nccl 2.18.3 following the documentation on nvidia's official website. I ran `dpkg -l | grep libnccl` and got 
```
ii  libnccl-dev                                2.18.3-1+cuda12.2                       amd64        NVIDIA Collective Communication Library (NCCL) Development Files
ii  libnccl2                                   2.18.3-1+cuda12.2                       amd64        NVIDIA Collective Communication Library (NCCL) Runtime
``` 

I also set environment variable in `/etc/profile`. The tail of /etc/profile is
```
export CUDA_HOME=/usr/local/cuda-12.2
export PATH=$PATH:$CUDA_HOME/bin
export LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64:/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
```

But the error still occurred. :(

**Additional Information**

In  conda env with pytorch 2.01 and cuda 11.8, I ran
```
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.nccl.version())
```
and got
```
2.0.1
True
(2, 14, 3)
```

In conda env with pytorch nightly and cuda 11.8, I ran same code but got
```
2.1.0.dev20230815
False
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 4
      2 print(torch.__version__)
      3 print(torch.cuda.is_available())
----> 4 print(torch.cuda.nccl.version())

File [~/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/cuda/nccl.py:35](https://vscode-remote+ssh-002dremote-002b10-002e236-002e11-002e64.vscode-resource.vscode-cdn.net/home/baoxuanlin/code/llama-recipes/~/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/cuda/nccl.py:35), in version()
     34 def version():
---> 35     ver = torch._C._nccl_version()
     36     major = ver >> 32
     37     minor = (ver >> 16) & 65535

AttributeError: module 'torch._C' has no attribute '_nccl_version'
```

I did my best to describe the problem and the environment, but it still might not be clear. If you need more information, please tell me directly. Thanks!

### Error logs

This is full stack when I ran sample fine-tuning code with pytorch nightly.
```
(llama2-nightly) baoxuanlin@ise-SYS-420GP-TNR:~$ torchrun --nnodes 1 --nproc_per_node 3  /home/baoxuanlin/code/llama-recipes/llama_finetuning.py --enable_fsdp --model_name /home/baoxuanlin/code/llama2_weights_hf/7B --output_dir /home/baoxuanlin/code/llama2_finetune
[2023-08-17 19:43:57,059] torch.distributed.run: [WARNING] 
[2023-08-17 19:43:57,059] torch.distributed.run: [WARNING] *****************************************
[2023-08-17 19:43:57,059] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2023-08-17 19:43:57,059] torch.distributed.run: [WARNING] *****************************************

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
CUDA SETUP: Loading binary /home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
CUDA SETUP: Loading binary /home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
CUDA SETUP: Loading binary /home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/baoxuanlin/code/llama-recipes/llama_finetuning.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import packaging
/home/baoxuanlin/code/llama-recipes/llama_finetuning.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import packaging
/home/baoxuanlin/code/llama-recipes/llama_finetuning.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import packaging
Traceback (most recent call last):
  File "/home/baoxuanlin/code/llama-recipes/llama_finetuning.py", line 253, in <module>
    fire.Fire(main)
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/baoxuanlin/code/llama-recipes/llama_finetuning.py", line 57, in main
    setup()
  File "/home/baoxuanlin/code/llama-recipes/utils/train_utils.py", line 295, in setup
    dist.init_process_group("nccl")
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1268, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
Traceback (most recent call last):
  File "/home/baoxuanlin/code/llama-recipes/llama_finetuning.py", line 253, in <module>
    fire.Fire(main)
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/baoxuanlin/code/llama-recipes/llama_finetuning.py", line 57, in main
    setup()
  File "/home/baoxuanlin/code/llama-recipes/utils/train_utils.py", line 295, in setup
    dist.init_process_group("nccl")
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1268, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
Traceback (most recent call last):
  File "/home/baoxuanlin/code/llama-recipes/llama_finetuning.py", line 253, in <module>
    fire.Fire(main)
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/baoxuanlin/code/llama-recipes/llama_finetuning.py", line 57, in main
    setup()
  File "/home/baoxuanlin/code/llama-recipes/utils/train_utils.py", line 295, in setup
    dist.init_process_group("nccl")
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1268, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
[2023-08-17 19:44:02,068] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 37341) of binary: /home/baoxuanlin/anaconda3/envs/llama2-nightly/bin/python
Traceback (most recent call last):
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0.dev20230815', 'console_scripts', 'torchrun')())
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/baoxuanlin/anaconda3/envs/llama2-nightly/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/baoxuanlin/code/llama-recipes/llama_finetuning.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-08-17_19:44:02
  host      : ise-SYS-420GP-TNR
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 37342)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-08-17_19:44:02
  host      : ise-SYS-420GP-TNR
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 37343)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-17_19:44:02
  host      : ise-SYS-420GP-TNR
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 37341)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

### Expected behavior

I want to run code without any error message~

Thank you!

**Comment by huangwei2913** [comment]
在进行分布式训练的时候，出现问题真的是太正常了。这个应该是nvidia通信库的问题，我看到你使用的是nightly版本的pytorch，可以考虑用下stable版本的，另外，如果实在不行，还能折腾下以MPI作为分布式通信库的方法。

**Comment by BaoBaoGitHub** [comment]
> 在进行分布式训练的时候，出现问题真的是太正常了。这个应该是nvidia通信库的问题，我看到你使用的是nightly版本的pytorch，可以考虑用下stable版本的，另外，如果实在不行，还能折腾下以MPI作为分布式通信库的方法。

好的，谢谢你。
有使用stable版本的fsdp+lora，但是会报错（不是分布式训练的错误）。
使用nightly版本，是因为多GPU微调的文档中有提到同时使用fsdp+lora需要nightly版本。
至于MPI，我会去了解一下。

**Comment by HamidShojanazeri** [comment]
this seems to be stale issue and not able to repro, closing this pls feel free to re-open if still seeing the issue.
