### ISSUE TITLE
convert_llama_weights_to_hf.py  json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by munitioner** [meta-llama/llama-recipes#150]
### System Info

colab   GPU：v100

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

![微信截图_20230829170647](https://github.com/facebookresearch/llama-recipes/assets/14157458/68c86120-5577-44db-81ba-af26ced834a7)

### Error logs

2023-08-29 08:19:08.150890: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/convert_llama_weights_to_hf.py", line 318, in <module>
    main()
  File "/content/convert_llama_weights_to_hf.py", line 306, in main
    write_model(
  File "/content/convert_llama_weights_to_hf.py", line 92, in write_model
    params = read_json(os.path.join(input_base_path, "params.json"))
  File "/content/convert_llama_weights_to_hf.py", line 75, in read_json
    return json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Expected behavior

!python convert_llama_weights_to_hf.py \
    --input_dir /content/llama/llama-2-7b --model_size 7B --output_dir /content/llama/models_hf/7B

**Comment by HamidShojanazeri** [comment]
@munitioner you wont need to convert the weights, you can just get the converted weights from HF hub, https://github.com/facebookresearch/llama-recipes#where-to-find-the-models

**Comment by ujaved** [comment]
i'm also running this issue trying to run quickstart notebook

**Comment by wukaixingxp** [comment]
Hi! Please check [getting-the-meta-llama-models](https://github.com/meta-llama/llama-recipes?tab=readme-ov-file#getting-the-meta-llama-models) section for more info!
