### ISSUE TITLE
Size mismatch when running inference.py with samsum example.

### ISSUE THREAD

**Issue by KemalDrop** [meta-llama/llama-recipes#179]
### System Info

torch              2.0.1+cu118
CUDA            12.0
GPU               Nvidia A10G

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

When I use the inference script provided in the examples with the command ```python inference.py meta-llama/Llama-2-7b-chat-hf --prompt_file samsum_prompt.txt``` I get the following error.

### Error logs

```
Traceback (most recent call last):
  File "/home/ubuntu/kemal/llama-recipes/examples/inference.py", line 140, in <module>
    fire.Fire(main)
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/kemal/llama-recipes/examples/inference.py", line 108, in main
    outputs = model.generate(
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/transformers/generation/utils.py", line 1648, in generate
    return self.sample(
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/transformers/generation/utils.py", line 2730, in sample
    outputs = self(
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 838, in forward
    logits = self.lm_head(hidden_states)
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/accelerate/hooks.py", line 286, in pre_forward
    set_module_tensor_to_device(
  File "/opt/conda/envs/llama-2/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 281, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([32000, 4096]) in "weight" (which has shape torch.Size([32001, 4096])), this look incorrect.
```

### Expected behavior

A generated response.

**Comment by mreso** [comment]
Hi @KemalDrop are you trying to run a model that was trained a while ago? I ran into this issue too and retraining my model solved the issue for me. I did not investigate the issue further but it seems to be related to the new accelerator release including this PR: https://github.com/huggingface/accelerate/pull/1731

**Comment by mreso** [comment]
Oh, just saw you're trying the stock model. Let me have a look into this.

**Comment by pruksmhc** [comment]
Following

**Comment by pruksmhc** [comment]
Explicitly specifying the padding length worked for me. 

cat ../examples/samsum_prompt.txt | python ../examples/inference.py  --model_name  /workspace/llama/transformers/llama-3-7b  --peft_model tmp/llama-output/ --max_padding_length 4096

**Comment by KemalDrop** [comment]
Yes I am using ```meta-llama/Llama-2-7b-chat``` model directly from huggingface. @pruksmhc that is just a hack not the solution but thanks anyway, will try that!

**Comment by mreso** [comment]
Just submitted #196 which will mitigate the issue. Though this will probably only work in this limited case of batch_size=1. Will try to revisit this soon to provide a batched example.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
