### ISSUE TITLE
Error in training using FSDP and PEFT

### ISSUE THREAD

**Issue by singhalshikha518** [meta-llama/llama-recipes#182]
### System Info

torch              2.2.0.dev20230907+cu118
torchaudio         2.2.0.dev20230907+cu118
torchvision        0.17.0.dev20230907+cu118
CUDA - 11.8
Number of GPUs - 5 A100(40GB)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Error while fine tuning using FSDP + PEFT

### Error logs

torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 203613 closing signal SIGTERM
[2023-09-08 10:21:20,648] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 203614 closing signal SIGTERM
[2023-09-08 10:21:20,650] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 203616 closing signal SIGTERM
[2023-09-08 10:21:22,992] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 0 (pid: 203612) of binary: /home/stsingha/llama_fsdp/bin/python3.9
Traceback (most recent call last):
  File "/home/stsingha/llama_fsdp/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/stsingha/llama_fsdp/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/stsingha/llama_fsdp/lib/python3.9/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/stsingha/llama_fsdp/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/stsingha/llama_fsdp/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/stsingha/llama_fsdp/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
llama_finetuning.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-08_10:21:20
  host      : aid-bm-gpu-b4-8-ad1-05.labsslurmsubnet.labsslurmvcn.oraclevcn.com
  rank      : 3 (local_rank: 3)
  exitcode  : -9 (pid: 203615)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 203615
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-08_10:21:20
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 203612)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 203612
============================================================

### Expected behavior

Fine tuned Model

**Comment by HamidShojanazeri** [comment]
@singhalshikha518 can you pls elaborate a bit more on what model size your are trying here, and the command you are running.

**Comment by singhalshikha518** [comment]
@HamidShojanazeri I am trying to fine tune llama2 7b chat hugging face model.
 https://huggingface.co/meta-llama/Llama-2-7b-chat-hf
 
 I used below command:
 torchrun --nnodes 1 --nproc_per_node 5  examples/example_finetuning.py --enable_fsdp --use_peft --peft_method lora --model_name huggingface_models/Llama-2-7b-chat-hf --pure_bf16 --output_dir //llama-recipes/output_models/9_sep

**Comment by singhalshikha518** [comment]
Also @HamidShojanazeri I have checked on single gpu it is working fine... problem occurs with FSDp+PEFT

**Comment by singhalshikha518** [comment]
@HamidShojanazeri - Could you please help on this?

**Comment by polym** [comment]
> exitcode : -9 (pid: 203612)
error_file: <N/A>
traceback : Signal 9 (SIGKILL) received by PID 203612

Based on the log provided, it appears that the process might be terminated by the system's OOM Killer. Can you run `dmesg` and provide the logs?

**Comment by Yuejun-GUO** [comment]
> exitcode : -9 (pid: 203612)
> error_file: <N/A>
> traceback : Signal 9 (SIGKILL) received by PID 203612

For me, the errors with ```exitcode : -9``` mostly happened when the cpu memory was insufficient. You can use ```htop``` to monitor the usage of cpu.

**Comment by wukaixingxp** [comment]
Hi! It seems that a solution has been provided to the issue and there has not been a follow-up conversation for a long time. I will close this issue for now and feel free to reopen it if you have any questions!
