### ISSUE TITLE
CUDA OOM with llama-7b without PEFT and Quantization

### ISSUE THREAD

**Issue by bkhanal-11** [meta-llama/llama-recipes#413]
### System Info

torch 2.2.1
cuda 12.0
gpu NVIDIA A100-SXM4-80GB

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

I wanted to finetune the llama-7b model without any PEFT and Quantization on Samsum dataset. However, I am getting Cuda out of memory error even with NVIDIA A100-SXM4-80GB. I would appreciate to know the spectification of hardware need to do so. Let me know if more information is needed.

### Error logs

```bash

(llvenv) root@C.10111143:~/llama2_finetuning/llama-recipes/recipes/finetuning$ python3 finetuning.py --model_name ../../../llama/llama-2-7b-hf --output_dir ./finetuned_model/
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:08<00:00,  2.69s/it]
--> Model ../../../llama/llama-2-7b-hf

--> ../../../llama/llama-2-7b-hf has 6738.415616 Million params

--> Training Set Length = 14732
--> Validation Set Length = 818
Preprocessing dataset: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14732/14732 [00:04<00:00, 3267.54it/s]
Preprocessing dataset: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 818/818 [00:00<00:00, 3190.10it/s]
/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/torch/cuda/memory.py:330: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(
Training Epoch: 1:   0%|                                                                                                                                                                   | 0/193 [00:00<?, ?it/s]Traceback (most recent call last):
  File "finetuning.py", line 8, in <module>
    fire.Fire(main)
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/llama2_finetuning/llama-recipes/src/llama_recipes/finetuning.py", line 268, in main
    results = train(
  File "/root/llama2_finetuning/llama-recipes/src/llama_recipes/utils/train_utils.py", line 103, in train
    loss = model(**batch).loss
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 1196, in forward
    outputs = self.model(
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 1016, in forward
    layer_outputs = decoder_layer(
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/llama2_finetuning/llvenv/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 755, in forward
    hidden_states = residual + hidden_states
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacity of 79.15 GiB of which 154.62 MiB is free. Process 4010816 has 78.99 GiB memory in use. Of the allocated memory 77.61 GiB is allocated by PyTorch, and 61.19 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Training Epoch: 1:   0%|                                                                                                                                                                   | 0/193 [00:05<?, ?it/s]```

### Expected behavior

The finetuning should have worked with the memory I had available.

**Comment by Matrixxxxxxxx** [comment]
Single A100 80G is not enough. I tested it and also got CUDA oom.
I also tried A100 40G * 5, that worked fine.

**Comment by HamidShojanazeri** [comment]
@bkhanal-11 you would need 2x80GB or 4x40GB if you want to do full fine-tuning without PEFT and quantization.

**Comment by bkhanal-11** [comment]
> @bkhanal-11 you would need 2x80GB or 4x40GB if you want to do full fine-tuning without PEFT and quantization.

Thank you for the information.
