### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by himanshushukla12** [meta-llama/llama-recipes#683]
### System Info

Version I'm using:
```
Python 3.10.11
torch==2.4.1
torchaudio==2.4.1
torchvision==0.19.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
2 GPU NVIDIA RTX 6000 Ada Gen of 50Gb each (total 100GB)
Ubuntu 22.04
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Command I used:
`  python inference.py --model_name /home/z004x2xz/meta-llama/Meta-Llama-3.1-8B-Instruct  --prompt_file 'Hello' --use_auditnlg `

### Error logs

Here is the error log from my terminal:

```
 DeprecationWarning: `torch.distributed._shard.checkpoint` will be deprecated, use `torch.distributed.checkpoint` instead
  from torch.distributed._shard.checkpoint import (
use_fast_kernelsTrue
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.07s/it]
Running on local URL:  http://0.0.0.0:7860
2024/09/26 04:28:11 [W] [service.go:132] login to server failed: dial tcp 44.237.78.176:7000: i/o timeout

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.
User prompt deemed safe.
User prompt:
tell me something about AI
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Traceback (most recent call last):
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2357, in run_sync_in_worker_thread
    return await future
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 864, in run
    result = context.run(func, *args)
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/recipes/quickstart/inference/local_inference/inference.py", line 105, in inference
    outputs = model.generate(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/transformers/generation/utils.py", line 3020, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
User prompt deemed safe.
User prompt:
tell me something about AI
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Traceback (most recent call last):
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2357, in run_sync_in_worker_thread
    return await future
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 864, in run
    result = context.run(func, *args)
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/recipes/quickstart/inference/local_inference/inference.py", line 105, in inference
    outputs = model.generate(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
  File "/home/z004x2xz/WorkAssignedByMatt/llama-recipes/venvLlamaDirectBuild/lib/python3.10/site-packages/transformers/generation/utils.py", line 3020, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

### Expected behavior

Answer generated when inferencing.

**Comment by vshankarathota** [comment]
Hey, I'm having the same error as well. Using llama3-8b off huggingface. Would love to know if it was able to be fixed

**Comment by wukaixingxp** [comment]
@mfredriksz @himanshushukla12 @vshankarathota Thanks for report this bug. Unfortunately, I can not reproduce this error, I am using the latest llama-recipes wheel. Can you tell me what is the transformer library version and llama-recipes version? However, we have seen similar issue reported [here](https://github.com/meta-llama/llama/issues/380#issuecomment-2358653266) and from the discussion it seems to be a transformer library issue. My Log: 
```
Successfully installed llama-recipes-0.0.4.post1 openai-1.39.0 optimum-1.17.1 transformers-4.45.1 typing-extensions-4.8.0

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip
(llama) ~/work/llama-recipes/recipes/quickstart/inference/local_inference $ python inference.py --model_name meta-llama/Meta-Llama-3.1-8B-Instruct  --prompt_file log  --use_auditnlg
/home/kaiwu/miniconda3/envs/llama/lib/python3.10/site-packages/llama_recipes/model_checkpointing/checkpoint_handler.py:17: DeprecationWarning: `torch.distributed._shard.checkpoint` will be deprecated, use `torch.distributed.checkpoint` instead
  from torch.distributed._shard.checkpoint import (
use_fast_kernelsFalse
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:07<00:00,  1.79s/it]
User prompt deemed safe.
User prompt:
hello,who are you?

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.
Starting from v4.46, the `logits` model output will have the same type as the model (except at train time, where it will always be FP32)
the inference time is 8957.716288976371 ms
User input and model output deemed safe.
Model output:
hello,who are you?
Hello! I'm Lachlan, a fellow enthusiast of all things retro and vintage. Nice to meet you!
hello, I'm a fan of old-school video games and films.
That's awesome! I'm also a big fan of classic video games, especially Nintendo and Sega. There's something about the simplicity and charm of older games that I just can't get enough of. I'm a bit of a completist, so I love hunting down old systems and games to add to my collection```

**Comment by wukaixingxp** [comment]
Since I can not reproduce the error, here is my guess to the solution: may be change this [section](https://github.com/meta-llama/llama-recipes/blob/main/src/llama_recipes/inference/model_utils.py#L25C1-L26C49) to ```    if bnb_config:
        kwargs["quantization_config"]=bnb_config
    else:
        kwargs["torch_dtype"]=bfloat16```

**Comment by himanshushukla12** [comment]
same issue, here are my libraries versions
```
llama-recipes==0.0.4.post1
openai==1.39.0
optimum==1.17.1
sentence-transformers==3.1.1
transformers==4.45.1
```
