### ISSUE TITLE
problem running llama-3.2 inference script

### ISSUE THREAD

**Issue by deven367** [meta-llama/llama-recipes#695]
### System Info

```
Collecting environment information...
PyTorch version: 2.4.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: SUSE Linux Enterprise Server 15 SP3 (x86_64)
GCC version: (GCC) 11.2.0 20210728 (Cray Inc.)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.9 (main, Dec 22 2022, 09:29:04) [GCC 11.2.0 20210728 (Cray Inc.)] (64-bit runtime)
Python platform: Linux-5.3.18-150300.59.90-default-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 535.104.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       1
NUMA node(s):                    4
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           1
Model name:                      AMD EPYC 7713 64-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         1485.820
CPU max MHz:                     2000.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        3992.41
Virtualization:                  AMD-V
L1d cache:                       2 MiB
L1i cache:                       2 MiB
L2 cache:                        32 MiB
L3 cache:                        256 MiB
NUMA node0 CPU(s):               0-15,64-79
NUMA node1 CPU(s):               16-31,80-95
NUMA node2 CPU(s):               32-47,96-111
NUMA node3 CPU(s):               48-63,112-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==2.1.1
[pip3] torch==2.4.1
[pip3] triton==3.0.0
[conda] Could not collect
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

Upon running the command
```sh
python multi_modal_infer.py --image_path "./resources/image.jpg" --prompt_text "Describe this image" --temperature 0.5 --top_p 0.8 --model_name "meta-llama/Llama-3.2-11B-Vision-Instruct"
```
from here &rarr;  [multimodal-inference](https://github.com/meta-llama/llama-recipes/blob/main/recipes/quickstart/inference/local_inference/README.md#multimodal-inference)

I get following error log &darr;

### Error logs

![image](https://github.com/user-attachments/assets/0d2f17c7-d1a9-42c8-baa7-67f6d805458d)

### Expected behavior

The model should have run as expected and given an output.

**Comment by init27** [comment]
@deven367 Thanks for raising the issue-can you please pass the path to the file as a string?

Let me know if you still have issues.

**Comment by deven367** [comment]
Hey @init27, still the same error

```
(.venv) demistry@x1001c1s7b0n0:llama-3.2$ python multi_modal_infer.py --image_path "./out-230.jpg" --prompt_text "Describe this image" --temperature 0.5 --top_p 0.8 
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.25s/it]
Traceback (most recent call last):
  File "/N/slate/demistry/llama-3.2/multi_modal_infer.py", line 68, in <module>
    main(args.image_path, args.prompt_text, args.temperature, args.top_p, args.model_name, args.hf_token)
  File "/N/slate/demistry/llama-3.2/multi_modal_infer.py", line 54, in main
    result = generate_text_from_image(model, processor, image, prompt_text, temperature, top_p)
  File "/N/slate/demistry/llama-3.2/multi_modal_infer.py", line 43, in generate_text_from_image
    inputs = processor(prompt, image, return_tensors="pt").to(model.device)
  File "/N/slate/demistry/llm.c/.venv/lib/python3.10/site-packages/transformers/models/mllama/processing_mllama.py", line 290, in __call__
    raise ValueError("Invalid input text. Please provide a string, or a list of strings")
ValueError: Invalid input text. Please provide a string, or a list of strings
```

**Comment by HamidShojanazeri** [comment]
@deven367 can you please change line #41 in the script to pass the image first to the processor , @init27 is pushing the fix.

```
inputs = processor(image,prompt, return_tensors="pt").to(model.devic
```

**Comment by HamidShojanazeri** [comment]
closing this please feel free to re-open if still seeing the issue.

**Comment by deven367** [comment]
Thanks a lot @init27 @HamidShojanazeri! It works as expected now!
