### ISSUE TITLE
RuntimeError: operator torchvision::nms does not exist

### ISSUE THREAD

**Issue by mZhenz** [meta-llama/llama-recipes#710]
### System Info

torch                                    2.4.1+cu124
torchaudio                               2.0.2+cu118
torchvision                              0.19.1+rocm6.1

GPU Type: A800
#GPU: 8
CUDA Version:
(base) root@sft-llama3-2-master-0:~/workspace-0/llama-recipes# nvidia-smi
Sun Oct  6 07:01:58 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

when running official llama3.2 training scripts

torchrun --nnodes 1 --nproc_per_node 8 recipes/quickstart/finetuning/finetuning.py \
    --enable_fsdp \
    --lr 1e-5  \
    --num_epochs 3 \
    --batch_size_training 2 \
    --model_name /path/to/Llama-3.2-11B-Vision \
    --dist_checkpoint_root_folder ./finetuned_model \
    --dist_checkpoint_folder fine-tuned  \
    --use_fast_kernels \
    --dataset "custom_dataset" \
    --custom_dataset.test_split "test" \
    --custom_dataset.file "recipes/quickstart/finetuning/datasets/ocrvqa_dataset.py" \
    --run_validation True \
    --batching_strategy padding

### Error logs
`W1006 06:59:19.627556 140218511484736 torch/distributed/run.py:779]
W1006 06:59:19.627556 140218511484736 torch/distributed/run.py:779] *****************************************
W1006 06:59:19.627556 140218511484736 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
W1006 06:59:19.627556 140218511484736 torch/distributed/run.py:779] *****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1764, in _get_module
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1764, in _get_module
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1764, in _get_module
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1764, in _get_module
        return importlib.import_module("." + module_name, self.__name__)return importlib.import_module("." + module_name, self.__name__)

  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
return importlib.import_module("." + module_name, self.__name__)
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/processing_auto.py", line 28, in <module>
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/processing_auto.py", line 28, in <module>
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/processing_auto.py", line 28, in <module>
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
    from ...image_processing_utils import ImageProcessingMixin
from ...image_processing_utils import ImageProcessingMixin  File "/opt/conda/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 21, in <module>
from ...image_processing_utils import ImageProcessingMixin
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/opt/conda/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 21, in <module>
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 21, in <module>
      File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/processing_auto.py", line 28, in <module>
from .image_transforms import center_crop, normalize, rescale
from .image_transforms import center_crop, normalize, rescale  File "/opt/conda/lib/python3.8/site-packages/transformers/image_transforms.py", line 22, in <module>

      File "/opt/conda/lib/python3.8/site-packages/transformers/image_transforms.py", line 22, in <module>
from .image_transforms import center_crop, normalize, rescale
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_transforms.py", line 22, in <module>
        from ...image_processing_utils import ImageProcessingMixinfrom .image_utils import (

from .image_utils import (  File "/opt/conda/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 21, in <module>
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_utils.py", line 58, in <module>

      File "/opt/conda/lib/python3.8/site-packages/transformers/image_utils.py", line 58, in <module>
from .image_utils import (
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_utils.py", line 58, in <module>
    from .image_transforms import center_crop, normalize, rescale
      File "/opt/conda/lib/python3.8/site-packages/transformers/image_transforms.py", line 22, in <module>
    from torchvision.transforms import InterpolationModefrom torchvision.transforms import InterpolationMode
      File "/opt/conda/lib/python3.8/site-packages/torchvision/__init__.py", line 10, in <module>

from torchvision.transforms import InterpolationMode  File "/opt/conda/lib/python3.8/site-packages/torchvision/__init__.py", line 10, in <module>

  File "/opt/conda/lib/python3.8/site-packages/torchvision/__init__.py", line 10, in <module>
    from .image_utils import (
from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip  File "/opt/conda/lib/python3.8/site-packages/transformers/image_utils.py", line 58, in <module>

      File "/opt/conda/lib/python3.8/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip  File "/opt/conda/lib/python3.8/site-packages/torchvision/_meta_registrations.py", line 164, in <module>

  File "/opt/conda/lib/python3.8/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
    from torchvision.transforms import InterpolationMode
  File "/opt/conda/lib/python3.8/site-packages/torchvision/__init__.py", line 10, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 654, in register
    def meta_nms(dets, scores, iou_threshold):
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 654, in register
    def meta_nms(dets, scores, iou_threshold):
from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 654, in register

  File "/opt/conda/lib/python3.8/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 654, in register
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1764, in _get_module
        use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)

      File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 154, in _register_fake
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 154, in _register_fake
use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 154, in _register_fake
    handle = entry.abstract_impl.register(func_to_register, source)
  File "/opt/conda/lib/python3.8/site-packages/torch/_library/abstract_impl.py", line 31, in register
        handle = entry.abstract_impl.register(func_to_register, source)use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)

  File "/opt/conda/lib/python3.8/site-packages/torch/_library/abstract_impl.py", line 31, in register
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 154, in _register_fake
    handle = entry.abstract_impl.register(func_to_register, source)
  File "/opt/conda/lib/python3.8/site-packages/torch/_library/abstract_impl.py", line 31, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError    : if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):operator torchvision::nms does not exist

The above exception was the direct cause of the following exception:

RuntimeError    Traceback (most recent call last):
: handle = entry.abstract_impl.register(func_to_register, source)  File "recipes/quickstart/finetuning/finetuning.py", line 5, in <module>
operator torchvision::nms does not exist

  File "/opt/conda/lib/python3.8/site-packages/torch/_library/abstract_impl.py", line 31, in register

The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):  File "recipes/quickstart/finetuning/finetuning.py", line 5, in <module>

RuntimeError: operator torchvision::nms does not exist

The above exception was the direct cause of the following exception:

if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
Traceback (most recent call last):
RuntimeError  File "recipes/quickstart/finetuning/finetuning.py", line 5, in <module>
: operator torchvision::nms does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "recipes/quickstart/finetuning/finetuning.py", line 5, in <module>
    return importlib.import_module("." + module_name, self.__name__)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/processing_auto.py", line 28, in <module>
    from ...image_processing_utils import ImageProcessingMixin
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 21, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_transforms.py", line 22, in <module>
    from .image_utils import (
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_utils.py", line 58, in <module>
    from torchvision.transforms import InterpolationMode
  File "/opt/conda/lib/python3.8/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
  File "/opt/conda/lib/python3.8/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 654, in register
    use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 154, in _register_fake
    handle = entry.abstract_impl.register(func_to_register, source)
  File "/opt/conda/lib/python3.8/site-packages/torch/_library/abstract_impl.py", line 31, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "recipes/quickstart/finetuning/finetuning.py", line 5, in <module>
    from llama_recipes.finetuning import main
  File "/home/jovyan/workspace-0/llama-recipes/src/llama_recipes/finetuning.py", line 19, in <module>
    from llama_recipes.finetuning import main
  File "/home/jovyan/workspace-0/llama-recipes/src/llama_recipes/finetuning.py", line 19, in <module>
        from llama_recipes.finetuning import mainfrom llama_recipes.finetuning import main

  File "/home/jovyan/workspace-0/llama-recipes/src/llama_recipes/finetuning.py", line 19, in <module>
  File "/home/jovyan/workspace-0/llama-recipes/src/llama_recipes/finetuning.py", line 19, in <module>
    from llama_recipes.finetuning import main
  File "/home/jovyan/workspace-0/llama-recipes/src/llama_recipes/finetuning.py", line 19, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1755, in __getattr__
    value = getattr(module, name)
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1754, in __getattr__
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1755, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1766, in _get_module
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
    value = getattr(module, name)
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1754, in __getattr__
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1755, in __getattr__
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto.processing_auto because of the following error (look up to see its traceback):
operator torchvision::nms does not exist
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1766, in _get_module
    value = getattr(module, name)
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1754, in __getattr__
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto.processing_auto because of the following error (look up to see its traceback):
operator torchvision::nms does not exist
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1766, in _get_module
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1755, in __getattr__
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto.processing_auto because of the following error (look up to see its traceback):
operator torchvision::nms does not exist
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
    value = getattr(module, name)
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1754, in __getattr__
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1755, in __getattr__
        module = self._get_module(self._class_to_module[name])value = getattr(module, name)

  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1766, in _get_module
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1754, in __getattr__
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto.processing_auto because of the following error (look up to see its traceback):
operator torchvision::nms does not exist
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1766, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto.processing_auto because of the following error (look up to see its traceback):
operator torchvision::nms does not exist
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1764, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/processing_auto.py", line 28, in <module>
    from ...image_processing_utils import ImageProcessingMixin
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 21, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_transforms.py", line 22, in <module>
    from .image_utils import (
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_utils.py", line 58, in <module>
    from torchvision.transforms import InterpolationMode
  File "/opt/conda/lib/python3.8/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
  File "/opt/conda/lib/python3.8/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 654, in register
    use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 154, in _register_fake
    handle = entry.abstract_impl.register(func_to_register, source)
  File "/opt/conda/lib/python3.8/site-packages/torch/_library/abstract_impl.py", line 31, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "recipes/quickstart/finetuning/finetuning.py", line 5, in <module>
    from llama_recipes.finetuning import main
  File "/home/jovyan/workspace-0/llama-recipes/src/llama_recipes/finetuning.py", line 19, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1755, in __getattr__
    value = getattr(module, name)
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1754, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1766, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto.processing_auto because of the following error (look up to see its traceback):
operator torchvision::nms does not exist
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1764, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/processing_auto.py", line 28, in <module>
    from ...image_processing_utils import ImageProcessingMixin
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 21, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_transforms.py", line 22, in <module>
    from .image_utils import (
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_utils.py", line 58, in <module>
    from torchvision.transforms import InterpolationMode
  File "/opt/conda/lib/python3.8/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
  File "/opt/conda/lib/python3.8/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 654, in register
    use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 154, in _register_fake
    handle = entry.abstract_impl.register(func_to_register, source)
  File "/opt/conda/lib/python3.8/site-packages/torch/_library/abstract_impl.py", line 31, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "recipes/quickstart/finetuning/finetuning.py", line 5, in <module>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1764, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/processing_auto.py", line 28, in <module>
    from llama_recipes.finetuning import main
  File "/home/jovyan/workspace-0/llama-recipes/src/llama_recipes/finetuning.py", line 19, in <module>
    from ...image_processing_utils import ImageProcessingMixin
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 21, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_transforms.py", line 22, in <module>
    from .image_utils import (
  File "/opt/conda/lib/python3.8/site-packages/transformers/image_utils.py", line 58, in <module>
    from torchvision.transforms import InterpolationMode
  File "/opt/conda/lib/python3.8/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
  File "/opt/conda/lib/python3.8/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 654, in register
    use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)
  File "/opt/conda/lib/python3.8/site-packages/torch/library.py", line 154, in _register_fake
    handle = entry.abstract_impl.register(func_to_register, source)
  File "/opt/conda/lib/python3.8/site-packages/torch/_library/abstract_impl.py", line 31, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "recipes/quickstart/finetuning/finetuning.py", line 5, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1755, in __getattr__
    from llama_recipes.finetuning import main
  File "/home/jovyan/workspace-0/llama-recipes/src/llama_recipes/finetuning.py", line 19, in <module>
    value = getattr(module, name)
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1754, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1766, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto.processing_auto because of the following error (look up to see its traceback):
operator torchvision::nms does not exist
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1755, in __getattr__
    value = getattr(module, name)
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1754, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1766, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto.processing_auto because of the following error (look up to see its traceback):
operator torchvision::nms does not exist
E1006 06:59:22.587260 140218511484736 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 979) of binary: /opt/conda/bin/python3.8
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
recipes/quickstart/finetuning/finetuning.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-06_06:59:22
  host      : aisc-rewrite-sft-llama3-2-master-0
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 980)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-10-06_06:59:22
  host      : aisc-rewrite-sft-llama3-2-master-0
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 981)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-10-06_06:59:22
  host      : aisc-rewrite-sft-llama3-2-master-0
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 982)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-10-06_06:59:22
  host      : aisc-rewrite-sft-llama3-2-master-0
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 983)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-10-06_06:59:22
  host      : aisc-rewrite-sft-llama3-2-master-0
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 984)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-10-06_06:59:22
  host      : aisc-rewrite-sft-llama3-2-master-0
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 985)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-10-06_06:59:22
  host      : aisc-rewrite-sft-llama3-2-master-0
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 986)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-06_06:59:22
  host      : aisc-rewrite-sft-llama3-2-master-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 979)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================`

### Expected behavior

Could you provide the exact version of the package used? It seems like there are something wrong with the torchvision version.

**Comment by mZhenz** [comment]
fixed

**Comment by wukaixingxp** [comment]
According to [this post](https://discuss.pytorch.org/t/runtimeerror-operator-torchvision-nms-does-not-exist/192829/2), please make sure the `torch` and  `torchvision` share the same cuda version, which is also the version of the cuda driver. It will be easier if you create a new conda env and just `pip install llama-recipes`, it should handle all the things for you.
